WIP 增加分版本的package引用和framework引用
dotnet-campus/SourceYard pull request #113
Opened 2021-11-18 08:56 UTC by lindexi

See https://github.com/dotnet-campus/SourceYard/pull/111

2021-11-18 09:59 UTC, lindexi commented
See https://github.com/dotnet/msbuild/issues/3787

2021-11-19 00:48 UTC, lindexi commented
多个框架分别使用不同的 NuGet 包完成

![图片](https://user-images.githubusercontent.com/16054566/142519823-fd0090d7-19f9-471e-8326-95ae03150b7f.png)

2021-11-19 01:36 UTC, lindexi commented
支持多框架依赖

![图片](https://user-images.githubusercontent.com/16054566/142543056-d35ac665-1ea9-45da-939e-8d60d56b4815.png)

2021-11-19 12:17 UTC, walterlv requested changes

2021-11-19 12:43 UTC, walterlv requested changes

2021-11-19 12:43 UTC, walterlv commented on src/dotnetCampus.SourceYard/Context/MultiTargetingPackageInfo.cs
> +                if (targetFrameworks != null && string.IsNullOrWhiteSpace(targetFrameworks) is false)
建议是 bool 类型的时候用 `!` 而不是 `is false`，避免某天你想对一个委托执行的返回值判断 bool 时忘记调用这个委托了，导致判断这个委托是否是 false。类似下面这样：

```csharp
object a = () => { };
if (a is false)
{

}
```

2021-11-19 12:43 UTC, walterlv commented on src/dotnetCampus.SourceYard/Context/MultiTargetingPackageInfo.cs
> +                    if (targetFrameworks.Contains(t.TargetFramework) is false)
net462 和 net46 也是包含关系，net6.1 和 net6 也是包含关系

2021-11-19 12:53 UTC, lindexi commented on docs/zh-cn/Behavior.md
> +### DisableSourcePackageAutoPrivateAssets
这里作为谨慎使用的属性，使用双重否定

2021-12-08 11:53 UTC, walterlv approved these changes

2021-12-08 12:59 UTC, merged